default:
  outputs:
    dev:
      dataset: aws_mwaa_dataset
      job_execution_timeout_seconds: 300
      job_retries: 1
      location: US
      method: oauth
      priority: interactive
      project: gurppup-123
      threads: 4
      type: bigquery
  target: dev
